# Generated by Django 3.0.8 on 2020-08-02 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_product_short_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='short_descexit',
        ),
    ]
